version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: uilet_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - uilet_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: uilet_backend
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_KEY=${JWT_KEY}
    ports:
      - "8080:8080"
    networks:
      - uilet_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uilet_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - uilet_network
    restart: unless-stopped

networks:
  uilet_network:
    driver: bridge

volumes:
  postgres_data: 